# Generated by Django 5.1.3 on 2024-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
